### ISSUE TITLE
waypoint file missing for autonomous mode

### ISSUE THREAD

**Issue by iacChris** [augcog/ROAR-DeCal#11]
As title says, currently the repo does not have waypoint file required for autonomous mode. Maybe we should consider either put it in the repo/data folder or provide a script to generate waypoints automatically.

**Comment by wuxiaohua1011** [comment]
This file should be downloaded from google drive to avoid this repo gets overwhelmingly large 

@zhenjiasun , can you include instruction in documentation for where to download this
