### ISSUE TITLE
Write a keyboard controller for Agent

### ISSUE THREAD

**Issue by wuxiaohua1011** [augcog/ROAR-DeCal#2]
Current [Keyboard controller](https://github.com/augcog/ROAR-DeCal/blob/master/carla_client/util/keyboard_control.py) is adapted from Carla, which depends on Carla. 

We probably don't need that much detailed functions such as light blinking etc. 

Would like a controller that just does the basics:
1. Control longitudinal velocity
2. Control Latitudinal Velocity

This controller should be placed in `roar_autonomous_system/util/keyboard_control.py`

**Comment by iacChris** [comment]
I will take a look and see what I can do.

**Comment by iacChris** [comment]
Per Allen's suggestion, this issue is closed.
