### ISSUE TITLE
Implement MPC module & Incorporate with Neural Networks

### ISSUE THREAD

**Issue by iacChris** [augcog/ROAR-DeCal#9]
As title says.

**Comment by wuxiaohua1011** [comment]
probbaly not NN for now, just a MPC controller plz

**Comment by iacChris** [comment]
A working demo is at [mpc_control](https://github.com/augcog/ROAR-DeCal/tree/mpc_control) branch, and the accompanying [video](https://youtu.be/At2f2fnY_vo). The current work is steady at a speed limit of 100 km/h. We can tuning parameters or using NN to improve performance in the future.

**Comment by wuxiaohua1011** [comment]
Great work! Let's work on merging that branch to master. First i wanted to merge it with the [michael](https://github.com/augcog/ROAR-DeCal/tree/michael) branch as it contains a better and clearer framework. Can you work on that?

**Comment by wuxiaohua1011** [comment]
Actually, let me revise my previous comment as i've merged the michael branch with master already, can you sync with master branch and make sure that the MPC controller works?

**Comment by iacChris** [comment]
kk, I will work on this for this week.
